NCI-GDC/gdcdatamodel

- setup.py
The required libraries are now open source ,which means they can be clone via https, not ssh.  This should hopefully fix travis setup.
> chore(deps): use https not ssh

- gdcdatamodel/models/submission.py
Defer potentially expensive loads until access.  This incurs a second trip to the database if the fields are accessed, however the latency to fetch the field outweighs the latency of the second trip
> defer expensive loads

- gdcdatamodel/models/submission.py
- migrations/async_transactions.py
Add `TransactionLog.closed` for  [API-32](https://jira.opensciencedatacloud.org/browse/API-32).
tested in https://github.com/NCI-GDC/gdcapi/pull/592
riders:
- adds indexes for new fields
> feat(tx_log): tx_log.closed

- gdcdatamodel/models/caching.py
- test/test_cache_related_cases.py
Updates the case cache strategy to explicitly delete old cache edges and create new cache edges.  
Previously, code was simply setting the association proxy, which will naively emitted an UPDATE statement for collisions.  Since we don't want to emit UPDATEs, this patch calculates the edges that _should_ be there, DELETEs any that _are_ there that shouldn't be, and INSERTs any _aren't_ there.
r? @philloooo
> fix(case-cache): remove UPDATE calls

- .travis.yml
- bin/destroy_and_setup_psqlgraph.py
- gdcdatamodel/models/__init__.py
- gdcdatamodel/models/indexes.py
- gdcdatamodel/models/submission.py
- migrations/index_secondary_keys.py
- test/conftest.py
- test/test_indexes.py
We can get approximately two orders of magnitude speedup on certain frequently used classes of queries by adding indexes on the text representation of the json fields defined as secondary keys in the dictionary.
```
SELECT count(*) FROM node_case WHERE (lower(node_case._props ->> 'submitter_id') LIKE 'tcga-c9' || '%%');
Time: 12.159 ms
%time g.nodes().filter(Node._props['submitter_id'].astext.startswith('TCGA-C9-A4')).count()
Wall time: 3.94 s
```
```
SELECT count(*) FROM node_case WHERE (lower(node_case._props ->> 'submitter_id') LIKE 'tcga-c9' || '%%');
Time: 0.604 ms
%time g.nodes().filter(Node._props['submitter_id'].astext.startswith('TCGA-C9-A4')).count()
CPU times: user 17 ms, sys: 3.78 ms, total: 20.8 ms
Wall time: 39.2 ms
```
> feat(indexes): index (->>) and lower(->>) on secondary keys

- .travis.yml
- migrations/test_update_case_cache.py
- migrations/update_case_cache.py
Some entities were created with a bug in the case cache cascading logic.  Add a migration to refresh the relationships to cases.
Addresses [DAT-200](https://jira.opensciencedatacloud.org/browse/DAT-200).
> feat(case-cache): update stale _related_cases

- migrations/update_case_cache_append_only.py
Server-side update case cache for all entities
1) Seed direct relationships from level L1 (1 step from case)
2) Visit all nodes in levels stepping out from case and for each
entity in that level L, add the related case edges from all
parents in level L-1 that do not already exist in level L
r? @NCI-GDC/ucdevs @philloooo @christiandompierre
> chore(case-cache): update_case_cache_append_only

- migrations/set_null_edge_columns.py
- migrations/update_case_cache_append_only.py
This migration updates all case cache relationships, however it inserted
null values for acl, props, and sysan. This does not violate a null
constraint but did break a downstream assumption about edges.
- fix: set columns to empty, rather than null
```python
from set_null_edge_columns import set_null_edge_columns
set_null_edge_columns(g)
```
> fix(migrations): fix update_case_cache_append_only

- gdcdatamodel/validators/json_validators.py
when a json schema is defined with `oneOf`, the error.message doesn't give useful information:
```
In [5]: validator = Draft4Validator({'properties': {'name': {'type': ['number', 'string'], 'oneOf': [{'enum': ['
...: abc']}, {'type': 'number'}]}}})
In [6]: for e in validator.iter_errors({'name': '123'}):
...:     print e.message
...:     print e.context
...:     
...:     
'123' is not valid under any of the given schemas
[<ValidationError: "'123' is not one of ['abc']">, <ValidationError: "'123' is not of type 'number'">]
```
This checks if there is any context for this error, and add the context to the error message.
So it's
```
'123' is not valid under any of the given schemas: '123' is not one of ['abc'] and '123' is not of type 'number'
```
instead of 
```
'123' is not valid under …
```
> chore(validator): improve error message

- gdcdatamodel/models/__init__.py
- gdcdatamodel/validators/graph_validators.py
- gdcdatamodel/validators/json_validators.py
- setup.py
[dictionaryutils.dictionary](https://github.com/uc-cdis/dictionaryutils/blob/master/dictionaryutils/dictionary.py) by default just load gdcdictionary, but allows rerun `init` to load with another dictionary
The change is backward compatible
> feat(dict): add dictionaryutils

- setup.py
Root node and DataRelease node came with the introduction of 2.0. Also pinning third party library versions that way seems like you intend to install the package from pypi.
> fix(version): bump dictionaryutils version

- gdcdatamodel/models/__init__.py
The gdcdictionary uses oneOf as a field to indicate a property of a node can be one or more different data types. This was not handled to create and validate nodes in the gdcdatamodel.
cc @philloooo
> fix(tt-888): interpret the oneOf field for types

- bin/destroy_and_setup_psqlgraph.py
- gdcdatamodel/models/misc.py
Adds report_data column to filereports table
Useful SQL queries
```sql
-- add new column to hold report data
ALTER TABLE public.filereport ADD COLUMN report_data jsonb;
-- add index to report_data column using gin (see: https://www.postgresql.org/docs/9.1/textsearch-indexes.html)
CREATE INDEX filereport_report_data_idx
ON public.filereport
USING gin
(report_data);
```
> feat(file_reports): add report_data column to filereports

- gdcdatamodel/models/__init__.py
- test/test_cache_related_cases.py
- test/test_datamodel.py
Only update `updated_datetime` if a node's own properties change. Don't update it when new edges are attached.
This prevents some potential issues with concurrent data submissions. Currently, if new children are created under the same parent concurrently, there can be conflicts updating the parent's `updated_datetime`. With this change, the `updated_datetime` won't be touched, so there won't be any conflict. I set up a parallel test in Sheepdog that submits a bunch of child nodes concurrently and verified that I was able to do so.
We should confirm that we want the business logic to work like this before we consider merging it, but in the meantime, the changes are here.
> fix(API-767): restrict updated_datetime changes

- gdcdatamodel/models/__init__.py
- gdcdatamodel/models/indexes.py
- migrations/update_case_cache_append_only.py
- migrations/update_legacy_states.py
`Node.label` and `Edge.label` is an `SQLAlchemy` `hybrid_property`. Previous versions for `SQLAlchemy` allows for resolving `hybrid_property` when called as a class property, but recent versions stopped this behavior (Not sure which version this happened) requiring class instances.
> fix(edge_factory): use get_label instead of label

- requirements.txt
- setup.py
Bumps datamodels to latest dictionary, this helps validate that the changes in the dictionary can be used for table migrations and works ok with psqlgraph
> chore(version): bump version to 2.1.0

- .travis.yml
- docker-compose-ci.yaml
- gdcdatamodel/validators/json_validators.py
- test/__init__.py
- test/test_gdc_postgres_admin.py
- test/test_validators.py
- tox.ini
See [DEV-259](https://jira.opensciencedatacloud.org/browse/DEV-259) for more details. Also minor clean ups in travis and adds test for py3.8, skips admin scripts tests on jenkins too, so tests there passes
> fix(json validator): fix json validation error reporting for array values

- .travis.yml
- gdcdatamodel/models/versioning.py
- setup.py
- test/test_node_tagging.py
Fixes issue where the function versioning.compute_tag generates generates different tag values for python2 and python3. The source of the difference was string representation in python2.
This blocks this PR https://github.com/NCI-GDC/biowcs/pull/221
> DEV-941: use six.ensure_str to fix tag mismatch issue

- gdcdatamodel/models/__init__.py
- gdcdatamodel/models/versioning.py
- test/unit/test_tagging.py
**Issue**: tag computation relies on the previously computed tag of the parent node, sometimes this value can be wrong even when trying to fix the generated tag, sometimes the old tag (wrong tag) is used instead of the newly fixed tags. This happened a lot during export of the v36 nodes.
**Fix**: remove the use of the parent's tag and force a complete recompute every time.
> remove parent tag caching

- requirements.txt
- setup.py
pip-compile 5.5.0 and python3.5 were used for this. Testing different
Python versions seemed to have mixed results. Using 3.5 caused the least
amount of changes which leads me to believe this is what we used last
time.
> chore(pins): update dr32 final pins

- gdcdatamodel/models/__init__.py
- gdcdatamodel/models/versioning.py
- test/schema/basic.yaml
- test/unit/test_tagging.py
Add implementation that ignores nodes with certain values for certain fields while generating a tag. These fields are configured via the dictionary. A sample configuration is also included for testing purposes.
* Adds is_taggable method to every node that supports versioning. This returns true only if a tag can be generated for the node
* Omit tag generation for nodes with is_taggable false
* Also omit parent nodes with is_taggable false while generating tag for child nodes
> DEV-1035: Add support for skipping nodes during tagging/versioning
