NCI-GDC/gdcdatamodel

setup.py
Update to latest dictionary version.
=> chore(deps): update to latest dictionary

gdcdatamodel/xml_mappings/tcga_clinical.yaml
fixes https://jira.opensciencedatacloud.org/browse/DAT-51
=> fix(bmi): DAT-51 convert from cm to m for height

gdcdatamodel/models/submission.py, migrations/async_transactions.py
Preliminary changes required to support [API-15](https://jira.opensciencedatacloud.org/browse/API-15) specified [here](https://wiki.oicr.on.ca/display/GDCSPECS/Asynchronous+Submission+Transactions) for https://github.com/NCI-GDC/gdcapi/pull/552.
=> feat(submission): async transaction columns/migration

setup.py
Bumping for updates to psqlgraph.
=> chore(psqlgraph): Bump psqlgraph dependency

gdcdatamodel/models/__init__.py, gdcdatamodel/models/notifications.py, migrations/notifications.py, setup.py
Creates model for [API-17](https://jira.opensciencedatacloud.org/browse/API-17).
=> feat(notificaitons): add model and migration

setup.py
bump for new analyte codes.
r? @allisonheath
=> chore(dictionary): DAT-170 update dictionary

setup.py
Bump for new methylation nodes in NCI-GDC/gdcdictionary#157
r? @allisonheath
=> chore(dictionary): Bump dictionary for DAT-111

setup.py
=> chore(avro): Remove avro

setup.py
Just update dictionary pin to latest.
=> bump dictionary

setup.py
Bumps dep for dictionary update adding `primary_site` and `disease_type` for case.
=> feat(deps): Bump dictionary for new case fields

setup.py
update with dictionary fixes from https://github.com/NCI-GDC/gdcdictionary/pull/190
=> update dictionary dependency

gdcdatamodel/models/submission.py
Update TransactionLog indexes.
=> fix project_id_idx, add created_datetime_idx

migrations/update_legacy_states.py
Addresses [DAT-471](https://jira.opensciencedatacloud.org/browse/DAT-471) and relates to [DAT-276](https://jira.opensciencedatacloud.org/browse/DAT-276).
Updates `state` and `file_state` to be consistent with [Entity States Specification](https://wiki.oicr.on.ca/display/GDCSPECS/Entity+States).
r? @madopal 
cc @seancannata
=> Add migration to update legacy states.

setup.py
=> update psqlgraph pin

gdcdatamodel/validators/graph_validators.py
Resolves #226.
Improve performance for validator by changing `GDCLinksValidator.validate` to take the entire list of entities at once, and so minimize the number of queries that need to be made (unless the validation fails, in which case the performance remains the same).
r? @philloooo 
Main thing to review:
- [This](https://github.com/NCI-GDC/gdcdatamodel/compare/fix/performance?expand=1#diff-e14c1f1dbf2878686bb5ff4da77b896cR138) is the correct condition to be checking for?
=> fix(performance): improve validator performance

setup.py
use https://github.com/NCI-GDC/psqlgraph/pull/136
=> chore(dependency): bump psqlgraph for psycopg fix

gdcdatamodel/xml_mappings/tcga_clinical.yaml
- Update tcga clinical mapping to support morphology default &
non lower case
=> fix(xml): Update tcga clinical mapping

gdcdatamodel/validators/graph_validators.py, gdcdatamodel/xml_mappings/tcga_biospecimen.yaml
- Add multiple paths in the yaml
- Fix link for parent_samples
=> feat(xml): Add multiple paths, fix parent_samples link name

setup.py
new dictionaryutils will have root and data release node schema pre-defined
db migration will need to happen
=> chore(dictutils): bump dictutils major version

gdcdatamodel/models/__init__.py, gdcdatamodel/xml_mappings/tcga_clinical.yaml, setup.py
Node Mappings used in sheepdog to parse XML, the mappings basically contains nodes and the xpath to pick up values from in the XML file. Since picking up the value for a given node has gotten fairly complex, I added an `evaluator` section that allows sheepdog to do custom logic for a given property
=> feat(xml_mappings): clinical xml mapping changes

gdcdatamodel/xml_mappings/tcga_clinical.yaml
Updated diagnosis.vital_status, exposure.prior_treatment and shortened the path for days_to_death
=> fix(xml): mapping updates

setup.py
- Update pin to new dictionary hotfix pin
=> chore(pins): Update pin to new dictionary hotfix pin

setup.py
=> release(1.18.0): bump version number to 1.18.0

setup.py
* Fixes errors when resolving dependencies (triggered during qclayer work)
=> [FIX] Release Python3 Deps

setup.py
-Correcting minor bump to micro bump for release/redfish
=> chore(redfish): tag

gdcdatamodel/models/__init__.py, gdcdatamodel/models/released_data.py, gdcdatamodel/models/studyrule.py, requirements.txt, setup.py
Add non graph models for StudyRule and ReleasedData
=> feat(study): add new studyrule and released_data models

requirements.txt
This pulls in changes to revert DICT-5
=> DEV-200 bump dependencies

gdcdatamodel/xml_mappings/tcga_clinical.yaml
https://jira.opensciencedatacloud.org/browse/DEV-488
Remove dictionary properties, used by sheepdog xml submission.
=> remove tumor_stage from xml mapping

requirements.txt, setup.py
https://jira.opensciencedatacloud.org/browse/DEV-488
=> bump dictionary version

requirements.txt, setup.py
https://jira.opensciencedatacloud.org/browse/DEV-488
=> final dict version for yertle

requirements.txt, setup.py, test/test_validators.py
=> chore(pins): update dictionary pins to 2.4.0-rc.1

requirements.txt, setup.py
Update gdcdictionary to 2.4.0-rc.3
=> chore(deps): bump gdcdictionary

requirements.txt, setup.py
Update final pins gdcdictionary to 2.4.0 and psqlgraph to 3.3.0
=> DEV-722: bump final boveri pins

requirements.txt, setup.py
=> DICT-171: bump gdcdictionary

.travis.yml
Update ubuntu distro to focal to fix build errors
=> Chore: Fix build errors in release/darwin

requirements.txt, setup.py
Removes dependencies on rc tags
=> DEV-1855: remove rc tag dependencies
